<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_miniCartLink</name>
   <tag></tag>
   <elementGuidId>112090ac-2d35-4512-810d-e483d6857a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>a.desk.cart-btn</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.desk.cart-btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
